TYPO3:
  FLOW3:
    persistence:
      # Options for the CouchDB backend
      backendOptions:
        # database: 'database_name'
        dataSourceName: 'http://127.0.0.1:5984'
        username: ~
        password: ~
        enableCouchdbLucene: no
        driver: ~
        path: ~
  CouchDB:
    log:
      queryLogger:
        # Disable query log by default
        backend: TYPO3\FLOW3\Log\Backend\NullBackend
        backendOptions: []
